/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrdinalItem = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'acquiredPrice' : IDL.Float64,
  'floorPrice' : IDL.Float64,
  'walletAddress' : IDL.Text,
  'imageUrl' : IDL.Text,
  'inscriptionId' : IDL.Text,
  'collectionName' : IDL.Text,
});
export const RuneHolding = IDL.Record({
  'id' : IDL.Text,
  'currentPrice' : IDL.Float64,
  'runeId' : IDL.Text,
  'walletAddress' : IDL.Text,
  'runeName' : IDL.Text,
  'avgBuyPrice' : IDL.Float64,
  'amount' : IDL.Float64,
});
export const TradeType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const Time = IDL.Int;
export const AssetType = IDL.Variant({
  'rune' : IDL.Null,
  'ordinal' : IDL.Null,
});
export const TradeRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'asset' : IDL.Text,
  'tradeType' : TradeType,
  'totalValue' : IDL.Float64,
  'walletAddress' : IDL.Text,
  'timestamp' : Time,
  'assetType' : AssetType,
  'price' : IDL.Float64,
  'amount' : IDL.Float64,
});
export const WalletType = IDL.Variant({
  'okx' : IDL.Null,
  'xverse' : IDL.Null,
  'oisy' : IDL.Null,
  'plug' : IDL.Null,
  'magicEden' : IDL.Null,
  'unisat' : IDL.Null,
  'bioniq' : IDL.Null,
});
export const WalletRecord = IDL.Record({
  'id' : IDL.Text,
  'walletType' : WalletType,
  'isConnected' : IDL.Bool,
  'addedAt' : Time,
  'address' : IDL.Text,
  'walletLabel' : IDL.Text,
});
export const WatchlistItem = IDL.Record({
  'id' : IDL.Text,
  'assetId' : IDL.Text,
  'alertEnabled' : IDL.Bool,
  'targetPrice' : IDL.Float64,
  'addedAt' : Time,
  'assetName' : IDL.Text,
  'assetType' : AssetType,
});
export const Preferences = IDL.Record({
  'theme' : IDL.Text,
  'notifications' : IDL.Bool,
  'currency' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'createdAt' : Time,
  'preferences' : Preferences,
  'avatarUrl' : IDL.Text,
});
export const PortfolioSnapshot = IDL.Record({
  'id' : IDL.Text,
  'ordinalsValueBtc' : IDL.Float64,
  'totalValueBtc' : IDL.Float64,
  'totalValueUsd' : IDL.Float64,
  'pnlDay' : IDL.Float64,
  'pnlWeek' : IDL.Float64,
  'timestamp' : Time,
  'pnlMonth' : IDL.Float64,
  'runesValueBtc' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addOrdinal' : IDL.Func([OrdinalItem], [], []),
  'addRuneHolding' : IDL.Func([RuneHolding], [], []),
  'addTradeRecord' : IDL.Func([TradeRecord], [], []),
  'addWallet' : IDL.Func([WalletRecord], [], []),
  'addWatchlistItem' : IDL.Func([WatchlistItem], [], []),
  'createProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getMyOrdinals' : IDL.Func([], [IDL.Vec(OrdinalItem)], []),
  'getMyProfile' : IDL.Func([], [UserProfile], []),
  'getMyRuneHoldings' : IDL.Func([], [IDL.Vec(RuneHolding)], []),
  'getMyTradeHistory' : IDL.Func([], [IDL.Vec(TradeRecord)], []),
  'getMyWallets' : IDL.Func([], [IDL.Vec(WalletRecord)], []),
  'getMyWatchlist' : IDL.Func([], [IDL.Vec(WatchlistItem)], []),
  'getPortfolioHistory' : IDL.Func([], [IDL.Vec(PortfolioSnapshot)], []),
  'savePortfolioSnapshot' : IDL.Func([PortfolioSnapshot], [], []),
  'updateMyProfile' : IDL.Func([IDL.Text, IDL.Text, Preferences], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrdinalItem = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'acquiredPrice' : IDL.Float64,
    'floorPrice' : IDL.Float64,
    'walletAddress' : IDL.Text,
    'imageUrl' : IDL.Text,
    'inscriptionId' : IDL.Text,
    'collectionName' : IDL.Text,
  });
  const RuneHolding = IDL.Record({
    'id' : IDL.Text,
    'currentPrice' : IDL.Float64,
    'runeId' : IDL.Text,
    'walletAddress' : IDL.Text,
    'runeName' : IDL.Text,
    'avgBuyPrice' : IDL.Float64,
    'amount' : IDL.Float64,
  });
  const TradeType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const Time = IDL.Int;
  const AssetType = IDL.Variant({ 'rune' : IDL.Null, 'ordinal' : IDL.Null });
  const TradeRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'asset' : IDL.Text,
    'tradeType' : TradeType,
    'totalValue' : IDL.Float64,
    'walletAddress' : IDL.Text,
    'timestamp' : Time,
    'assetType' : AssetType,
    'price' : IDL.Float64,
    'amount' : IDL.Float64,
  });
  const WalletType = IDL.Variant({
    'okx' : IDL.Null,
    'xverse' : IDL.Null,
    'oisy' : IDL.Null,
    'plug' : IDL.Null,
    'magicEden' : IDL.Null,
    'unisat' : IDL.Null,
    'bioniq' : IDL.Null,
  });
  const WalletRecord = IDL.Record({
    'id' : IDL.Text,
    'walletType' : WalletType,
    'isConnected' : IDL.Bool,
    'addedAt' : Time,
    'address' : IDL.Text,
    'walletLabel' : IDL.Text,
  });
  const WatchlistItem = IDL.Record({
    'id' : IDL.Text,
    'assetId' : IDL.Text,
    'alertEnabled' : IDL.Bool,
    'targetPrice' : IDL.Float64,
    'addedAt' : Time,
    'assetName' : IDL.Text,
    'assetType' : AssetType,
  });
  const Preferences = IDL.Record({
    'theme' : IDL.Text,
    'notifications' : IDL.Bool,
    'currency' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'createdAt' : Time,
    'preferences' : Preferences,
    'avatarUrl' : IDL.Text,
  });
  const PortfolioSnapshot = IDL.Record({
    'id' : IDL.Text,
    'ordinalsValueBtc' : IDL.Float64,
    'totalValueBtc' : IDL.Float64,
    'totalValueUsd' : IDL.Float64,
    'pnlDay' : IDL.Float64,
    'pnlWeek' : IDL.Float64,
    'timestamp' : Time,
    'pnlMonth' : IDL.Float64,
    'runesValueBtc' : IDL.Float64,
  });
  
  return IDL.Service({
    'addOrdinal' : IDL.Func([OrdinalItem], [], []),
    'addRuneHolding' : IDL.Func([RuneHolding], [], []),
    'addTradeRecord' : IDL.Func([TradeRecord], [], []),
    'addWallet' : IDL.Func([WalletRecord], [], []),
    'addWatchlistItem' : IDL.Func([WatchlistItem], [], []),
    'createProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getMyOrdinals' : IDL.Func([], [IDL.Vec(OrdinalItem)], []),
    'getMyProfile' : IDL.Func([], [UserProfile], []),
    'getMyRuneHoldings' : IDL.Func([], [IDL.Vec(RuneHolding)], []),
    'getMyTradeHistory' : IDL.Func([], [IDL.Vec(TradeRecord)], []),
    'getMyWallets' : IDL.Func([], [IDL.Vec(WalletRecord)], []),
    'getMyWatchlist' : IDL.Func([], [IDL.Vec(WatchlistItem)], []),
    'getPortfolioHistory' : IDL.Func([], [IDL.Vec(PortfolioSnapshot)], []),
    'savePortfolioSnapshot' : IDL.Func([PortfolioSnapshot], [], []),
    'updateMyProfile' : IDL.Func([IDL.Text, IDL.Text, Preferences], [], []),
  });
};

export const init = ({ IDL }) => { return []; };