/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AssetType = { 'rune' : null } |
  { 'ordinal' : null };
export interface OrdinalItem {
  'id' : string,
  'name' : string,
  'acquiredPrice' : number,
  'floorPrice' : number,
  'walletAddress' : string,
  'imageUrl' : string,
  'inscriptionId' : string,
  'collectionName' : string,
}
export interface PortfolioSnapshot {
  'id' : string,
  'ordinalsValueBtc' : number,
  'totalValueBtc' : number,
  'totalValueUsd' : number,
  'pnlDay' : number,
  'pnlWeek' : number,
  'timestamp' : Time,
  'pnlMonth' : number,
  'runesValueBtc' : number,
}
export interface Preferences {
  'theme' : string,
  'notifications' : boolean,
  'currency' : string,
}
export interface RuneHolding {
  'id' : string,
  'currentPrice' : number,
  'runeId' : string,
  'walletAddress' : string,
  'runeName' : string,
  'avgBuyPrice' : number,
  'amount' : number,
}
export type Time = bigint;
export interface TradeRecord {
  'id' : string,
  'status' : string,
  'asset' : string,
  'tradeType' : TradeType,
  'totalValue' : number,
  'walletAddress' : string,
  'timestamp' : Time,
  'assetType' : AssetType,
  'price' : number,
  'amount' : number,
}
export type TradeType = { 'buy' : null } |
  { 'sell' : null };
export interface UserProfile {
  'principal' : Principal,
  'username' : string,
  'createdAt' : Time,
  'preferences' : Preferences,
  'avatarUrl' : string,
}
export interface WalletRecord {
  'id' : string,
  'walletType' : WalletType,
  'isConnected' : boolean,
  'addedAt' : Time,
  'address' : string,
  'walletLabel' : string,
}
export type WalletType = { 'okx' : null } |
  { 'xverse' : null } |
  { 'oisy' : null } |
  { 'plug' : null } |
  { 'magicEden' : null } |
  { 'unisat' : null } |
  { 'bioniq' : null };
export interface WatchlistItem {
  'id' : string,
  'assetId' : string,
  'alertEnabled' : boolean,
  'targetPrice' : number,
  'addedAt' : Time,
  'assetName' : string,
  'assetType' : AssetType,
}
export interface _SERVICE {
  'addOrdinal' : ActorMethod<[OrdinalItem], undefined>,
  'addRuneHolding' : ActorMethod<[RuneHolding], undefined>,
  'addTradeRecord' : ActorMethod<[TradeRecord], undefined>,
  'addWallet' : ActorMethod<[WalletRecord], undefined>,
  'addWatchlistItem' : ActorMethod<[WatchlistItem], undefined>,
  'createProfile' : ActorMethod<[string, string], undefined>,
  'getMyOrdinals' : ActorMethod<[], Array<OrdinalItem>>,
  'getMyProfile' : ActorMethod<[], UserProfile>,
  'getMyRuneHoldings' : ActorMethod<[], Array<RuneHolding>>,
  'getMyTradeHistory' : ActorMethod<[], Array<TradeRecord>>,
  'getMyWallets' : ActorMethod<[], Array<WalletRecord>>,
  'getMyWatchlist' : ActorMethod<[], Array<WatchlistItem>>,
  'getPortfolioHistory' : ActorMethod<[], Array<PortfolioSnapshot>>,
  'savePortfolioSnapshot' : ActorMethod<[PortfolioSnapshot], undefined>,
  'updateMyProfile' : ActorMethod<[string, string, Preferences], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];