/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WalletRecord {
    id: string;
    walletType: WalletType;
    isConnected: boolean;
    addedAt: Time;
    address: string;
    walletLabel: string;
}
export interface RuneHolding {
    id: string;
    currentPrice: number;
    runeId: string;
    walletAddress: string;
    runeName: string;
    avgBuyPrice: number;
    amount: number;
}
export type Time = bigint;
export interface PortfolioSnapshot {
    id: string;
    ordinalsValueBtc: number;
    totalValueBtc: number;
    totalValueUsd: number;
    pnlDay: number;
    pnlWeek: number;
    timestamp: Time;
    pnlMonth: number;
    runesValueBtc: number;
}
export interface Preferences {
    theme: string;
    notifications: boolean;
    currency: string;
}
export interface TradeRecord {
    id: string;
    status: string;
    asset: string;
    tradeType: TradeType;
    totalValue: number;
    walletAddress: string;
    timestamp: Time;
    assetType: AssetType;
    price: number;
    amount: number;
}
export interface WatchlistItem {
    id: string;
    assetId: string;
    alertEnabled: boolean;
    targetPrice: number;
    addedAt: Time;
    assetName: string;
    assetType: AssetType;
}
export interface UserProfile {
    principal: Principal;
    username: string;
    createdAt: Time;
    preferences: Preferences;
    avatarUrl: string;
}
export interface OrdinalItem {
    id: string;
    name: string;
    acquiredPrice: number;
    floorPrice: number;
    walletAddress: string;
    imageUrl: string;
    inscriptionId: string;
    collectionName: string;
}
export enum AssetType {
    rune = "rune",
    ordinal = "ordinal"
}
export enum TradeType {
    buy = "buy",
    sell = "sell"
}
export enum WalletType {
    okx = "okx",
    xverse = "xverse",
    oisy = "oisy",
    plug = "plug",
    magicEden = "magicEden",
    unisat = "unisat",
    bioniq = "bioniq"
}
export interface backendInterface {
    addOrdinal(ordinal: OrdinalItem): Promise<void>;
    addRuneHolding(rune: RuneHolding): Promise<void>;
    addTradeRecord(trade: TradeRecord): Promise<void>;
    addWallet(wallet: WalletRecord): Promise<void>;
    addWatchlistItem(item: WatchlistItem): Promise<void>;
    createProfile(username: string, avatarUrl: string): Promise<void>;
    getMyOrdinals(): Promise<Array<OrdinalItem>>;
    getMyProfile(): Promise<UserProfile>;
    getMyRuneHoldings(): Promise<Array<RuneHolding>>;
    getMyTradeHistory(): Promise<Array<TradeRecord>>;
    getMyWallets(): Promise<Array<WalletRecord>>;
    getMyWatchlist(): Promise<Array<WatchlistItem>>;
    getPortfolioHistory(): Promise<Array<PortfolioSnapshot>>;
    savePortfolioSnapshot(snapshot: PortfolioSnapshot): Promise<void>;
    updateMyProfile(username: string, avatarUrl: string, preferences: Preferences): Promise<void>;
}
import type { AssetType as _AssetType, Time as _Time, TradeRecord as _TradeRecord, TradeType as _TradeType, WalletRecord as _WalletRecord, WalletType as _WalletType, WatchlistItem as _WatchlistItem } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addOrdinal(arg0: OrdinalItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrdinal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrdinal(arg0);
            return result;
        }
    }
    async addRuneHolding(arg0: RuneHolding): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRuneHolding(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRuneHolding(arg0);
            return result;
        }
    }
    async addTradeRecord(arg0: TradeRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTradeRecord(to_candid_TradeRecord_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTradeRecord(to_candid_TradeRecord_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addWallet(arg0: WalletRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWallet(to_candid_WalletRecord_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWallet(to_candid_WalletRecord_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addWatchlistItem(arg0: WatchlistItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWatchlistItem(to_candid_WatchlistItem_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWatchlistItem(to_candid_WatchlistItem_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0, arg1);
            return result;
        }
    }
    async getMyOrdinals(): Promise<Array<OrdinalItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrdinals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrdinals();
            return result;
        }
    }
    async getMyProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return result;
        }
    }
    async getMyRuneHoldings(): Promise<Array<RuneHolding>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRuneHoldings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRuneHoldings();
            return result;
        }
    }
    async getMyTradeHistory(): Promise<Array<TradeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTradeHistory();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTradeHistory();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWallets(): Promise<Array<WalletRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWallets();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWallets();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWatchlist(): Promise<Array<WatchlistItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWatchlist();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWatchlist();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioHistory(): Promise<Array<PortfolioSnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioHistory();
            return result;
        }
    }
    async savePortfolioSnapshot(arg0: PortfolioSnapshot): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePortfolioSnapshot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePortfolioSnapshot(arg0);
            return result;
        }
    }
    async updateMyProfile(arg0: string, arg1: string, arg2: Preferences): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_AssetType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetType): AssetType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_TradeRecord_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeRecord): TradeRecord {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_TradeType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeType): TradeType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_WalletRecord_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalletRecord): WalletRecord {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_WalletType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalletType): WalletType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_WatchlistItem_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WatchlistItem): WatchlistItem {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    asset: string;
    tradeType: _TradeType;
    totalValue: number;
    walletAddress: string;
    timestamp: _Time;
    assetType: _AssetType;
    price: number;
    amount: number;
}): {
    id: string;
    status: string;
    asset: string;
    tradeType: TradeType;
    totalValue: number;
    walletAddress: string;
    timestamp: Time;
    assetType: AssetType;
    price: number;
    amount: number;
} {
    return {
        id: value.id,
        status: value.status,
        asset: value.asset,
        tradeType: from_candid_TradeType_n16(_uploadFile, _downloadFile, value.tradeType),
        totalValue: value.totalValue,
        walletAddress: value.walletAddress,
        timestamp: value.timestamp,
        assetType: from_candid_AssetType_n18(_uploadFile, _downloadFile, value.assetType),
        price: value.price,
        amount: value.amount
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    walletType: _WalletType;
    isConnected: boolean;
    addedAt: _Time;
    address: string;
    walletLabel: string;
}): {
    id: string;
    walletType: WalletType;
    isConnected: boolean;
    addedAt: Time;
    address: string;
    walletLabel: string;
} {
    return {
        id: value.id,
        walletType: from_candid_WalletType_n23(_uploadFile, _downloadFile, value.walletType),
        isConnected: value.isConnected,
        addedAt: value.addedAt,
        address: value.address,
        walletLabel: value.walletLabel
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    assetId: string;
    alertEnabled: boolean;
    targetPrice: number;
    addedAt: _Time;
    assetName: string;
    assetType: _AssetType;
}): {
    id: string;
    assetId: string;
    alertEnabled: boolean;
    targetPrice: number;
    addedAt: Time;
    assetName: string;
    assetType: AssetType;
} {
    return {
        id: value.id,
        assetId: value.assetId,
        alertEnabled: value.alertEnabled,
        targetPrice: value.targetPrice,
        addedAt: value.addedAt,
        assetName: value.assetName,
        assetType: from_candid_AssetType_n18(_uploadFile, _downloadFile, value.assetType)
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): TradeType {
    return "buy" in value ? TradeType.buy : "sell" in value ? TradeType.sell : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rune: null;
} | {
    ordinal: null;
}): AssetType {
    return "rune" in value ? AssetType.rune : "ordinal" in value ? AssetType.ordinal : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    okx: null;
} | {
    xverse: null;
} | {
    oisy: null;
} | {
    plug: null;
} | {
    magicEden: null;
} | {
    unisat: null;
} | {
    bioniq: null;
}): WalletType {
    return "okx" in value ? WalletType.okx : "xverse" in value ? WalletType.xverse : "oisy" in value ? WalletType.oisy : "plug" in value ? WalletType.plug : "magicEden" in value ? WalletType.magicEden : "unisat" in value ? WalletType.unisat : "bioniq" in value ? WalletType.bioniq : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TradeRecord>): Array<TradeRecord> {
    return value.map((x)=>from_candid_TradeRecord_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WalletRecord>): Array<WalletRecord> {
    return value.map((x)=>from_candid_WalletRecord_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WatchlistItem>): Array<WatchlistItem> {
    return value.map((x)=>from_candid_WatchlistItem_n26(_uploadFile, _downloadFile, x));
}
function to_candid_AssetType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetType): _AssetType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TradeRecord_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeRecord): _TradeRecord {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TradeType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeType): _TradeType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_WalletRecord_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WalletRecord): _WalletRecord {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_WalletType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WalletType): _WalletType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_WatchlistItem_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WatchlistItem): _WatchlistItem {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    assetId: string;
    alertEnabled: boolean;
    targetPrice: number;
    addedAt: Time;
    assetName: string;
    assetType: AssetType;
}): {
    id: string;
    assetId: string;
    alertEnabled: boolean;
    targetPrice: number;
    addedAt: _Time;
    assetName: string;
    assetType: _AssetType;
} {
    return {
        id: value.id,
        assetId: value.assetId,
        alertEnabled: value.alertEnabled,
        targetPrice: value.targetPrice,
        addedAt: value.addedAt,
        assetName: value.assetName,
        assetType: to_candid_AssetType_n5(_uploadFile, _downloadFile, value.assetType)
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    asset: string;
    tradeType: TradeType;
    totalValue: number;
    walletAddress: string;
    timestamp: Time;
    assetType: AssetType;
    price: number;
    amount: number;
}): {
    id: string;
    status: string;
    asset: string;
    tradeType: _TradeType;
    totalValue: number;
    walletAddress: string;
    timestamp: _Time;
    assetType: _AssetType;
    price: number;
    amount: number;
} {
    return {
        id: value.id,
        status: value.status,
        asset: value.asset,
        tradeType: to_candid_TradeType_n3(_uploadFile, _downloadFile, value.tradeType),
        totalValue: value.totalValue,
        walletAddress: value.walletAddress,
        timestamp: value.timestamp,
        assetType: to_candid_AssetType_n5(_uploadFile, _downloadFile, value.assetType),
        price: value.price,
        amount: value.amount
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    walletType: WalletType;
    isConnected: boolean;
    addedAt: Time;
    address: string;
    walletLabel: string;
}): {
    id: string;
    walletType: _WalletType;
    isConnected: boolean;
    addedAt: _Time;
    address: string;
    walletLabel: string;
} {
    return {
        id: value.id,
        walletType: to_candid_WalletType_n9(_uploadFile, _downloadFile, value.walletType),
        isConnected: value.isConnected,
        addedAt: value.addedAt,
        address: value.address,
        walletLabel: value.walletLabel
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WalletType): {
    okx: null;
} | {
    xverse: null;
} | {
    oisy: null;
} | {
    plug: null;
} | {
    magicEden: null;
} | {
    unisat: null;
} | {
    bioniq: null;
} {
    return value == WalletType.okx ? {
        okx: null
    } : value == WalletType.xverse ? {
        xverse: null
    } : value == WalletType.oisy ? {
        oisy: null
    } : value == WalletType.plug ? {
        plug: null
    } : value == WalletType.magicEden ? {
        magicEden: null
    } : value == WalletType.unisat ? {
        unisat: null
    } : value == WalletType.bioniq ? {
        bioniq: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeType): {
    buy: null;
} | {
    sell: null;
} {
    return value == TradeType.buy ? {
        buy: null
    } : value == TradeType.sell ? {
        sell: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetType): {
    rune: null;
} | {
    ordinal: null;
} {
    return value == AssetType.rune ? {
        rune: null
    } : value == AssetType.ordinal ? {
        ordinal: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
